default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  prepared_statements: false

development:
  <<: *default
  url: postgresql://postgres.jcixfyhrvesbyjtuinxe:utmSIRAJ69hime%40lucy@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: postgresql://postgres.jcixfyhrvesbyjtuinxe:utmSIRAJ69hime%40lucy@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
